### ISSUE TITLE
not expand the view in some links

### ISSUE THREAD

**Issue by pokerface131G** [Decryptu/Better-CoinMarketCap#2]
Hi fatalicious56， 
I have used this plugin for some days. and it helps me a lot. 
thanks.

But still, in some places, it removes ads but not expand the view, such as  https://coinmarketcap.com/view/real-world-assets/ 
You see, the right area is blank. 
Because I add a lot of indicators to table,  I hope the plugin can expand the page so I can see all the columns. 
hehe.  
Hope you can understand. 

Bgs

**Comment by pokerface131G** [comment]
![2024-10-30_093828](https://github.com/user-attachments/assets/54eae93a-6821-4410-bc56-8f32660f277d)

**Comment by pokerface131G** [comment]
![Uploading 2024-10-30_093957.png…]()

**Comment by pokerface131G** [comment]
![2024-10-30_093957](https://github.com/user-attachments/assets/8f04aa23-1fbe-4a10-87f7-ab2cf4a5e0fd)

**Comment by Decryptu** [comment]
fixed in [1.3.0](https://github.com/Decryptu/Better-CoinMarketCap/releases/tag/1.3.0)
