### ISSUE TITLE
i try to use the code: style.css  in tampermonkey script.

### ISSUE THREAD

**Issue by pokerface131G** [Decryptu/Better-CoinMarketCap#3]
but the grid is always misaligned. did you know how to mod ? 

// ==UserScript==
// @name         CoinMarketCap Community Remover
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  隐藏CoinMarketCap页面上的社区部分，保持页面布局。
// @match        https://coinmarketcap.com/view/*
// @match        https://coinmarketcap.com/currencies/*
// @grant        none
// @run-at       document-start
// ==/UserScript==

(function() {
    'use strict';

    // 隐藏社区部分的函数
    const hideCommunitySection = () => {
        const communitySection = document.querySelector('div[data-module-name="Coin-Community"]');
        if (communitySection) {
            communitySection.style.display = 'none'; // 隐藏社区部分

            // 调整父容器的样式以防止错位
            const parentContainer = communitySection.closest('.full-width-layout');
            if (parentContainer) {
                parentContainer.style.gridTemplateColumns = '25% 75%'; // 确保其他列宽度保持一致
            }
        }
    };

    // 在DOM内容加载完成后运行隐藏函数
    document.addEventListener('DOMContentLoaded', hideCommunitySection);
})();
![2024-10-30_175403](https://github.com/user-attachments/assets/3329cc6d-4e82-4e85-86c0-fbc473340cae)

**Comment by Decryptu** [comment]
hello, cmc updated their front-end recently, maybe check the new extension code (1.3.0 release)
